version: '3.9'

services:

  config-server:
    container_name: config-server
    hostname: config-server
    build:
      context: ./Configuration/
      dockerfile: Dockerfile
    image: config-server:latest
    restart: on-failure
    expose:
      - 8888
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  eureka-server:
    container_name: eureka-server
    hostname: discovery-server
    build:
      context: ./Eureka/
      dockerfile: Dockerfile
    image: eureka-server:latest
    restart: on-failure
    expose:
      - 8999
    ports:
      - 8999:8999

    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:8999/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=4000
      - EUREKA_SERVER_RENEWAL_PERCENT_THRESHOLD=0.85
    networks:
      - app-network

  user-service:
    container_name: user-service
    build:
      context: ./UserManagement/user/
      dockerfile: Dockerfile
    image: user-service:latest
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://avnadmin:AVNS_ZLF4pMhUQz19ftLA3Sz@mysql-36fd5e58-etf-31e6.a.aivencloud.com:13331/defaultdb?ssl-mode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_ZLF4pMhUQz19ftLA3Sz
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_SERVER_URL=http://eureka-server:8999/eureka
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://user-service:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  appointment-service:
    container_name: appointment-service
    build:
      context: ./AppointmentManagement/
      dockerfile: Dockerfile
    image: appointment-service:latest
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://avnadmin:AVNS_mOZQBXvwz0I-NAeMgkB@appointment-gianes-9ebb.e.aivencloud.com:24334/defaultdb?ssl-mode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_mOZQBXvwz0I-NAeMgkB
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_SERVER_URL=http://eureka-server:8999/eureka
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://appointment-service:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  stressrelief-service:
    container_name: stressrelief-service
    build:
      context: ./StressReliefManagement/
      dockerfile: Dockerfile
    image: stressrelief-service:latest
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://avnadmin:AVNS_RCbR6rhl5mxqDKpsqvI@mysql-23b72a2b-azuretechtalk-94bb.g.aivencloud.com:10379/defaultdb?ssl-mode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_RCbR6rhl5mxqDKpsqvI
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_SERVER_URL=http://eureka-server:8999/eureka
    expose:
      - 8083
    ports:
      - 8083:8083
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://stressrelief-service:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  article-service:
    container_name: article-service
    build:
      context: ./ArticleManagement/ArticleManagement/
      dockerfile: Dockerfile
    image: article-service:latest
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://avnadmin:AVNS_oARMFA_a9EfKpb85b_B@article-logsmarter-f8c0.e.aivencloud.com:15491/defaultdb?ssl-mode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_oARMFA_a9EfKpb85b_B
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_SERVER_URL=http://eureka-server:8999/eureka
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://article-service:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10

    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    image: api-gateway:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8999/eureka
    expose:
      - 8089
    ports:
      - 8089:8089
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8089/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
